routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('', 'MasterController@home');
Route::get('/', 'MasterController@home');
Route::get('home', 'MasterController@home');
Route::get('/home', 'MasterController@home');

Route::resource('logistik','LogistikController');
Route::resource('laporan','LaporanController');
Route::resource('kategori','KategoriController');
Route::resource('pengungsi','PengungsiController');
Route::resource('donasi','DonasiController');
// Route::post('laporan.store2', 'LaporanController@store2');
Auth::routes();

Route::get('laporkan', 'MasterController@laporan');
Route::get('donasikan', 'MasterController@donasikan');
Route::post('/laporkan/proses', 'MasterController@store_laporan');
Route::post('/donasi/proses', 'MasterController@store_donasikan');
Route::get('tentang', 'MasterController@tentang');
Route::get('map', 'MasterController@map');
Route::get('dasbor', 'MasterController@dasbor');

app/Pengungsi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pengungsi extends Model{
  protected $fillable = [
    'id','nama_pengungsian','jumlah_pengungsi', 'alamat', 'daerah', 'lat', 'lng'
  ];
}

?>

app/Http/Controllers/PengungsiController.php
<?php

namespace App\Http\Controllers;

use App\Pengungsi;
use Illuminate\Http\Request;

class PengungsiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pengungsi = Pengungsi::latest()->paginate(5);

        return view('pengungsi.index',compact('pengungsi'))->with('i',(request()->input('page',1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('pengungsi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
          'nama_pengungsian' => 'required',
          'jumlah_pengungsi' => 'required',
          'alamat' => 'required',
          'daerah' => 'required',
          'lat' => 'required',
          'lng' => 'required'
        ]);

        Pengungsi::create($request->all());

        return redirect()->route('pengungsi.index')->with('success','Data berhasil ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Pengungsi $pengungsi)
    {
        return view('pengungsi.show',compact('pengungsi'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Pengungsi $pengungsi)
    {
        return view('pengungsi.edit',compact('pengungsi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pengungsi $pengungsi)
    {
        //
        $request->validate([
          'nama_pengungsian' => 'required',
          'jumlah_pengungsi' => 'required',
          'alamat' => 'required',
          'daerah' => 'required',
          'lat' => 'required',
          'lng' => 'required'
        ]);

        $pengungsi->update($request->all());

        return redirect()->route('pengungsi.index')->with('success','Data berhasil disunting.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pengungsi $pengungsi)
    {
        //
        $pengungsi->delete();

        return redirect()->route('pengungsi.index')->with('success','Data berhasil dihapus.');
    }
}

resources/views/pengungsi/create.blade.php
@extends('pengungsi.layout')
@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">Tambahkan Pengungsian</h4>
          <p class="card-category">Tambahkan data pengungsian ke dalam database</p>
        </div>
        <div class="card-body">
          <form action="{{ route('pengungsi.store') }}" method="POST">
              @csrf
               <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Nama Pengungsian :</strong>
                          <input type="text" name="nama_pengungsian" class="form-control" placeholder="Nama">
                      </div>
                      <div class="form-group">
                          <strong>Jumlah Pengungsi :</strong>
                          <input type="text" name="jumlah_pengungsi" class="form-control" placeholder="Jumlah Pengungsi">
                      </div>
                      <div class="form-group">
                          <strong>Alamat :</strong>
                          <input type="text" name="alamat" class="form-control" placeholder="Alamat">
                      </div>
                      <div class="form-group">
                          <strong>Daerah :</strong>
                          <input type="text" name="daerah" class="form-control" placeholder="Daerah">
                      </div>
                      <div class="form-group">
                          <div id="map" style="height: 400px;"></div>
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12 text-right pull-right">
                          <input type="hidden" name="lat" id="lat" class="form-control" placeholder="">
                          <input type="hidden" name="lng" id="lng" class="form-control" placeholder="">
                          <button type="submit" class="btn btn-success">Simpan</button>
                          <a class="btn btn-danger" href="{{ route('pengungsi.index') }}"> Kembali</a>
                  </div>
              </div>
          </form>
          <script>
          // Initialize and add the map
          function initMap() {

          var myLatlng = new google.maps.LatLng(-7.6655719,110.4200379);
          var mapProp = {
          center:myLatlng,
          zoom:15,
          mapTypeId:google.maps.MapTypeId.ROADMAP

          };
          var map=new google.maps.Map(document.getElementById("map"), mapProp);
          var marker = new google.maps.Marker({
            position: myLatlng,
            map: map,
            title: 'Hello World!',
            draggable:true
          });
          document.getElementById('lat').value= -7.6655719
          document.getElementById('lng').value= 110.4200379
          // marker drag event
          google.maps.event.addListener(marker,'drag',function(event) {
              document.getElementById('lat').value = event.latLng.lat();
              document.getElementById('lng').value = event.latLng.lng();
          });

          //marker drag event end
          google.maps.event.addListener(marker,'dragend',function(event) {
              document.getElementById('lat').value = event.latLng.lat();
              document.getElementById('lng').value = event.latLng.lng();
              /* alert("lat=>"+event.latLng.lat());
              alert("long=>"+event.latLng.lng()); */
          });

          }
          </script>
          <!--Load the API from the specified URL
          * The async attribute allows the browser to render the page while the API loads
          * The key parameter will contain your own API key (which is not needed for this tutorial)
          * The callback parameter executes the initMap() function
          -->
          <!-- <script async defer
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCYCl9g6BehrGK78Z082mXpb0jIPHHGwYQ&callback=initMap">
          </script> -->

        </div>
      </div>
    </div>
  </div>
</div>



@endsection

resources/views/pengungsi/edit.blade.php
@extends('pengungsi.layout')
@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">Sunting Kategori</h4>
          <p class="card-category">Ubah data kategori dalam database</p>
        </div>
        <div class="card-body">
          <form action="{{ route('kategori.update',$kategori->id) }}" method="POST">
              @csrf
              @method('PUT')
               <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Kategori :</strong>
                          <input type="text" name="kategori" value="{{$kategori->kategori}}" class="form-control" placeholder="Nama">
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12 text-right pull-right">
                          <button type="submit" class="btn btn-success">Simpan</button>
                          <a class="btn btn-danger" href="{{ route('kategori.index') }}"> Kembali</a>
                  </div>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/pengungsi/index.blade.php
@extends('pengungsi.layout')

@section('content')

<script>
function cari() {
// Declare variables
var input, filter, table, tr, td, i;
input = document.getElementById("input_search");
filter = input.value.toUpperCase();
table = document.getElementById("contentTable");
tr = table.getElementsByTagName("tr");

// Loop through all table rows, and hide those who don't match the search query
for (i = 0; i < tr.length; i++) {
	td = tr[i].getElementsByTagName("td")[2];
	if (td) {
		if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
			tr[i].style.display = "";
		} else {
			tr[i].style.display = "none";
		}
	}
}
}
</script>

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
            </div>
            <div class="pull-right">

            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
    <script>swal("{{ $message }}","","success")</script>

    @endif
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">

            <div class="row">
              <div class="col-md-9">
                  <h4 class="card-title ">Data Pengungsi</h4>
                  <p class="card-category"> Berikut merupakan data pengungsi</p>
              </div>
              <div class="col-md-3 pull-right">
                @guest
                @else
                  @if(Auth::user()->user_type=='BPBD')
                  <a class="btn btn-success" href="{{ route('pengungsi.create') }}"> Tambah Pengungsian</a>
                  @endif
                @endguest
                <input type="text" class="form-control text-white" id="input_search" onkeyup="cari()" placeholder="Pencarian berdasarkan nama pengungsian">
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table" id="contentTable">
                  <tr>
                      <th>No</th>
                      <!-- <th>ID</th> -->
                      <th>ID</th>
                      <th>Nama Pengungsian</th>
                      <th>Jumlah Pengungsi</th>
                      <th>Alamat</th>
                      <th>Daerah</th>
                      <th width="280px">Action</th>
                  </tr>
                  @foreach ($pengungsi as $product)
                  <tr>
                      <td>{{ ++$i }}</td>
                      <!-- <td>{{ $product->id }}</td> -->
                      <td>{{ $product->id }}</td>
                      <td>{{ $product->nama_pengungsian }}</td>
                      <td>{{ $product->jumlah_pengungsi }}</td>
                      <td>{{ $product->alamat }}</td>
                      <td>{{ $product->daerah }}</td>
                      <td>
                          <form action="{{ route('pengungsi.destroy',$product->id) }}" method="POST">
                              <a class="btn btn-info" href="{{ route('pengungsi.show',$product->id) }}"><i class="material-icons">search</i></a>
                              @guest
                              @else
                                @if(Auth::user()->user_type=='BPBD')
                              <a class="btn btn-primary" href="{{ route('pengungsi.edit',$product->id) }}"><i class="material-icons">edit</i></a>
                              @csrf
                              @method('DELETE')
                              <button type="submit" class="btn btn-danger"><i class="material-icons">delete</i></button>
                              @endif
                            @endguest
                          </form>
                      </td>
                  </tr>
                  @endforeach
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
      function confirmDelete(){
        event.preventDefault();
        Swal({
          title: 'Apakah anda yakin?',
          text: "Data yang dihapus tidak dapat dikembalikan",
          type: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Hapus',
          cancelButtonText: 'Batal',
        }).then((result) => {
          if (result.value) {
            Swal(
              'Data berhasil dihapus!',
              '',
              'success'
            )
            return true;
          }
          })
        }
  </script>

    {!! $pengungsi ->links() !!}
@endsection

resources/views/pengungsi/map.blade.php
@extends('pengungsi.layout_map')

@section('content')

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">Peta Pengungsian</h4>
              <p class="card-category">Pemetaan pengungsian dalam database</p>
            </div>
            <div class="card-body">
              <div class="col-xs-12 col-sm-12 col-md-12">
                  <div id="map" style="height: 400px;"></div>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12 text-right pull-right">
                <br>
                <a class="btn btn-danger" href="{{ route('kategori.index') }}"> Kembali</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
    var map;
     var markers = {!! json_encode($markers) !!}; //this should dump a javascript array object which does not need any extra interperting.
     var marks = []; //just incase you want to be able to manipulate this later

     function initMap() {
         map = new google.maps.Map(document.getElementById('map'), {
             center: {lat: -7.6655719, lng: 110.4200379},
             zoom: 11
         });

         for(var i = 0; i < markers.length; i++){
             marks[i] = addMarker(markers[i]);
         }
     }

     function addMarker(marker){
         var nama_pengungsian = marker.nama_pengungsian;
         var jumlah_pengungsi = marker.jumlah_pengungsi;
         var alamat = marker.alamat;
         var daerah = marker.daerah;
         var catatan = marker.catatan;
         var kategori = marker.kategori;

         var html = "<b> Nama tempat : " + nama_pengungsian + "</b> <br/>Jumlah Pengungsi : " + jumlah_pengungsi + " orang,<br/> <b>Butuh : </b>" + kategori + ", " + catatan + ",<br/>" + alamat + ",<br/>" + daerah;

         var markerLatlng = new google.maps.LatLng(parseFloat(marker.lat),parseFloat(marker.lng));


         var mark = new google.maps.Marker({
             map: map,
             position: markerLatlng,

         });

         var infoWindow = new google.maps.InfoWindow;
         google.maps.event.addListener(mark, 'click', function(){
             infoWindow.setContent(html);
             infoWindow.open(map, mark);
         });

         return mark;
     }

     function doNothing(){} //very appropriately named function. whats it for?


    </script>

    <!-- <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCYCl9g6BehrGK78Z082mXpb0jIPHHGwYQ&callback=initMap">
    </script> -->

@endsection

resources/views/pengungsi/show.blade.php
@extends('pengungsi.layout')

@section('content')

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">Rincian Data Pengungsi</h4>
              <p class="card-category">Rincian data pengungsi dalam database</p>
            </div>
            <div class="card-body">
              <div class="col-xs-12 col-sm-12 col-md-12">
                  <div class="form-group">
                      <strong>Pengungsian :</strong>
                      {{ $pengungsi->nama_pengungsian }}
                  </div>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12">
                  <div class="form-group">
                      <strong>Jumlah Pengungsi :</strong>
                      {{ $pengungsi->jumlah_pengungsi }}
                  </div>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12">
                  <div class="form-group">
                      <strong>Alamat :</strong>
                      {{ $pengungsi->alamat }}
                  </div>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12">
                  <div class="form-group">
                      <strong>Daerah :</strong>
                      {{ $pengungsi->daerah }}
                  </div>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12 text-right pull-right">
                <a class="btn btn-danger" href="{{ route('kategori.index') }}"> Kembali</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

@endsection