routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('', 'MasterController@home');
Route::get('/', 'MasterController@home');
Route::get('home', 'MasterController@home');
Route::get('/home', 'MasterController@home');

Route::resource('logistik','LogistikController');
Route::resource('laporan','LaporanController');
Route::resource('kategori','KategoriController');
Route::resource('pengungsi','PengungsiController');
Route::resource('donasi','DonasiController');
// Route::post('laporan.store2', 'LaporanController@store2');
Auth::routes();

Route::get('laporkan', 'MasterController@laporan');
Route::get('donasikan', 'MasterController@donasikan');
Route::post('/laporkan/proses', 'MasterController@store_laporan');
Route::post('/donasi/proses', 'MasterController@store_donasikan');
Route::get('tentang', 'MasterController@tentang');
Route::get('map', 'MasterController@map');
Route::get('dasbor', 'MasterController@dasbor');

app/Donasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Donasi extends Model{
  protected $fillable = [
    'id','donatur', 'kontak'
  ];
}

?>

app/Http/Controllers/DonasiController.php
<?php

namespace App\Http\Controllers;

use DB;
use App\Donasi;
use App\User;
use App\Pengungsi;
use App\Kategori;
use App\Logistik;
use Illuminate\Http\Request;

class DonasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $donasi = DB::table('donasis')
                      ->join('users','donasis.donatur','=','users.id')
                      ->join('logistiks','donasis.donatur','=','logistiks.sumber')
                      ->join('kategoris','kategoris.id','=','logistiks.kategori')
                      ->select('donasis.*','users.name','logistiks.nama','logistiks.stok','logistiks.kategori')
                      ->paginate('5');

        // dd($donasi);

        return view('donasi.index',compact('donasi'))->with('i',(request()->input('page',1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $lokasi = Pengungsi::all();
        $kategori = Kategori::all();
        $user = User::all();
        return view('donasi.create',compact('lokasi','kategori','user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
          'donatur' => 'required',
          'kontak'  => 'required',
        ]);

        Donasi::create($request->all());

        $request->validate([
          'nama' => 'required',
          'stok' => 'required',
          'kadaluarsa' => 'required',
          'kategori' => 'required',
          'daerah' => 'required',
          'sumber' => 'required'
        ]);

        Logistik::create($request->all());

        return redirect()->route('donasi.index')->with('success','Data berhasil ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Donasi $donasi)
    {
        return view('donasi.show',compact('donasi'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Donasi $donasi)
    {
        return view('donasi.edit',compact('donasi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Donasi $donasi)
    {
        //
        $request->validate([
          'donatur' => 'required',
          'kontak'  => 'required',
        ]);

        $donasi->update($request->all());

        return redirect()->route('donasi.index')->with('success','Data berhasil disunting.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Donasi $donasi)
    {
        //
        $donasi->delete();

        return redirect()->route('donasi.index')->with('success','Data berhasil dihapus.');
    }
}

resources/views/donasi/create.blade.php
@extends('donasi.layout')
@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">Tambahkan Donasi</h4>
          <p class="card-category">Tambahkan data donasi ke dalam database</p>
        </div>
        <div class="card-body">
          <form action="{{ route('donasi.store') }}" method="POST">
              @csrf
               <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Donatur :</strong>
                          <select class="form-control" name="donatur" id="donatur" onchange="return updateSumber(this.value)">
                            <option value="">Pilih Donatur Logistik</option>
                            @foreach ($user as $item)
                            <option value="{{$item->id}}">{{$item->name}}</option>
                            @endforeach
                          </select>
                      </div>
                  </div>
                  <input type="hidden" id="inputSumber" name="sumber" value=""/>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Kontak Donatur :</strong>
                          <input type="text" class="form-control" name="kontak" placeholder="Kontak">
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Nama Logistik:</strong>
                          <input type="text" name="nama" class="form-control" placeholder="Name">
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Stok:</strong>
                          <input type="text" class="form-control" name="stok" placeholder="stok">
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Kadaluarsa:</strong>
                          <input type="date" class="form-control" name="kadaluarsa" placeholder="kadaluarsa">
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Kategori:</strong>
                          <select class="form-control" name="kategori">
                            <option value="">Pilih Kebutuhan</option>
                            @foreach ($kategori as $product)
                            <option value="{{$product->id}}">{{$product->kategori}}</option>
                            @endforeach
                          </select>
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Daerah:</strong>
                          <!-- <input type="text" class="form-control" name="daerah" placeholder="daerah"> -->
                          <select class="form-control" name="daerah">
                            <option value="">Pilih Tempat Pengungsian</option>
                            @foreach ($lokasi as $item)
                            <option value="{{$item->id}}">{{$item->nama_pengungsian}}</option>
                            @endforeach
                          </select>
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12 text-right pull-right">
                          <button type="submit" class="btn btn-success">Simpan</button>
                          <a class="btn btn-danger" href="{{ route('donasi.index') }}"> Kembali</a>
                  </div>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  function updateSumber(val){
    document.getElementById('inputSumber').value = val;
  }
</script>

@endsection

resources/views/donasi/edit.blade.php
@extends('donasi.layout')
@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">Tambahkan Donasi</h4>
          <p class="card-category">Tambahkan data donasi ke dalam database</p>
        </div>
        <div class="card-body">
          <form action="{{ route('donasi.update',$donasi->id) }}" method="POST">
              @csrf
              @method('PUT')
               <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Nama Donatur :</strong>
                          <input type="text" name="donatur" value="{{$donasi->donatur}}" class="form-control" placeholder="Nama">
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Kontak :</strong>
                          <input type="text" class="form-control" value="{{$donasi->kontak}}" name="kontak" placeholder="Kontak">
                      </div>
                  </div>

                  <div class="col-xs-12 col-sm-12 col-md-12 text-right pull-right">
                          <button type="submit" class="btn btn-success">Simpan</button>
                          <a class="btn btn-danger" href="{{ route('donasi.index') }}"> Kembali</a>
                  </div>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/donasi/index.blade.php
@extends('donasi.layout')

@section('content')

<script>
function cari() {
// Declare variables
var input, filter, table, tr, td, i;
input = document.getElementById("input_search");
filter = input.value.toUpperCase();
table = document.getElementById("contentTable");
tr = table.getElementsByTagName("tr");

// Loop through all table rows, and hide those who don't match the search query
for (i = 0; i < tr.length; i++) {
	td = tr[i].getElementsByTagName("td")[1];
	if (td) {
		if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
			tr[i].style.display = "";
		} else {
			tr[i].style.display = "none";
		}
	}
}
}
</script>

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
            </div>
            <div class="pull-right">

            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <script>swal("{{ $message }}","","success")</script>

    @endif
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">

            <div class="row">
              <div class="col-md-9">
                  <h4 class="card-title ">Data Donasi</h4>
                  <p class="card-category"> Berikut merupakan data donasi</p>
              </div>
              <div class="col-md-3 pull-right">
                @guest
                @else
                  @if(Auth::user()->user_type=='BPBD')
                  <a class="btn btn-success" href="{{ route('donasi.create') }}"> Tambah Donasi</a>
                  @endif
                @endguest
                <input type="text" class="form-control text-white" id="input_search" onkeyup="cari()" placeholder="Pencarian berdasarkan donatur">
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table" id="contentTable">
                  <tr>
                      <th>No</th>
                      <!-- <th>ID</th> -->
                      <th>Nama Donatur</th>
                      <th>Kontak</th>
                      <th>Donasi</th>
                      <th>Stok</th>
                      <th>Kategori</th>
                      <th width="280px">Action</th>
                  </tr>
                  @foreach ($donasi as $product)
                  <tr>
                      <td>{{ ++$i }}</td>
                      <!-- <td>{{ $product->id }}</td> -->
                      <td>{{ $product->name }}</td>
                      <td>{{ $product->kontak }}</td>
                      <td>{{ $product->nama }}</td>
                      <td>{{ $product->stok }}</td>
                      <td>{{ $product->kategori }}</td>
                      <td>
                          <form action="{{ route('donasi.destroy',$product->id) }}" method="POST">
                              <a class="btn btn-info" href="{{ route('donasi.show',$product->id) }}"><i class="material-icons">search</i></a>
                              <a class="btn btn-primary" href="{{ route('donasi.edit',$product->id) }}"><i class="material-icons">edit</i></a>
                              @csrf
                              @method('DELETE')
                              <button type="submit" class="btn btn-danger"><i class="material-icons">delete</i></button>
                          </form>
                      </td>
                  </tr>
                  @endforeach
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
    function confirmDelete(){
      event.preventDefault();
      Swal({
        title: 'Apakah anda yakin?',
        text: "Data yang dihapus tidak dapat dikembalikan",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Hapus',
        cancelButtonText: 'Batal',
      }).then((result) => {
        if (result.value) {
          Swal(
            'Data berhasil dihapus!',
            '',
            'success'
          )
          return true;
        }
        })
      }
</script>

    {!! $donasi->links() !!}
@endsection

resources/views/donasi/layout.blade.php
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Sistem Distribusi Logistik - Mistik</title>
    <!-- Favicon -->
    <link href="{{URL::to('/dashboard')}}/img/brand/favicon.png" rel="icon" type="image/png">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- Icons -->
    <link href="{{URL::to('/dashboard')}}/vendor/nucleo/css/nucleo.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

    <link href="{{URL::to('/dashboard')}}/css/material-dashboard.css?v=2.1.1" rel="stylesheet" />
    <link href="{{URL::to('/dashboard')}}/demo/demo.css" rel="stylesheet" />
    <!--SweetAlert-->
    <script src="{{URL::to('/dashboard')}}/js/plugins/sweetalert2.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

</head>

<body>
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="../img/sidebar-1.jpg">
      <!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

      Tip 2: you can also add an image using data-image tag
  -->
      <div class="logo">
        <a href="#" class="simple-text logo-normal">
          INNO<strong>FICTION</strong>
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="/dasbor">
              <i class="material-icons">insert_chart</i>
              <p>Dasbor</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logistik">
              <i class="material-icons">dashboard</i>
              <p>Logistik</p>
            </a>
          </li>
          <li class="nav-item  ">
            <a class="nav-link" href="/map">
              <i class="material-icons">map</i>
              <p>Peta</p>
            </a>
          </li>
          @guest

          @else
            @if(Auth::user()->user_type=='Relawan')
            <li class="nav-item ">
              <a class="nav-link " href="/laporan">
                <i class="material-icons">description</i>
                <p>Laporan</p>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="/pengungsi">
                <i class="material-icons">supervisor_account</i>
                <p>Pengungsi</p>
              </a>
            </li>
            @elseif(Auth::user()->user_type=='Donatur')
            <li class="nav-item active ">
              <a class="nav-link " href="/donasi">
                <i class="material-icons">how_to_vote</i>
                <p>Donasi</p>
              </a>
            </li>
            @elseif(Auth::user()->user_type=='BPBD')
            <li class="nav-item ">
              <a class="nav-link" href="/laporan">
                <i class="material-icons">description</i>
                <p>Laporan</p>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="/pengungsi">
                <i class="material-icons">supervisor_account</i>
                <p>Pengungsi</p>
              </a>
            </li>
            <li class="nav-item active ">
              <a class="nav-link" href="/donasi">
                <i class="material-icons">how_to_vote</i>
                <p>Donasi</p>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/kategori">
                <i class="material-icons">storage</i>
                <p>Kategori</p>
              </a>
            </li>
            @endif
          @endguest
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <!-- <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">Dashboard</a>
          </div> -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a href="../" class="nav-link" role="button">
                  <i class="ni ni-collection d-lg-none"></i>
                  <span class="nav-link-inner--text">Beranda</span>
                </a>
              </li>
              <li class="nav-item">
                <a href="/logistik" class="nav-link" role="button">
                  <i class="ni ni-collection d-lg-none"></i>
                  <span class="nav-link-inner--text">Stok</span>
                </a>
              </li>
              @guest
              <li class="nav-item">
                  <a href="{{ route('login') }}" class="btn btn-neutral btn-icon">
                    <span class="btn-inner--icon">
                      <i class="fa fa-user-circle mr-2"></i>
                    </span>
                    <span class="nav-link-inner--text">{{ __('Login') }}</span>
                  </a>
              </li>
              @else
                @if(Auth::user()->user_type=='Relawan')
                <li class="nav-item">
                  <a href="/laporan" class="nav-link" role="button">
                    <i class="ni ni-collection d-lg-none"></i>
                    <span class="nav-link-inner--text">Laporan</span>
                  </a>
                </li>
                @elseif(Auth::user()->user_type=='Donatur')
                <li class="nav-item">
                  <a href="/donasi  " class="nav-link" role="button">
                    <i class="ni ni-collection d-lg-none"></i>
                    <span class="nav-link-inner--text">Donasi</span>
                  </a>
                </li>
                @elseif(Auth::user()->user_type=='BPBD')
                <li class="nav-item">
                  <a href="/laporan" class="nav-link" role="button">
                    <i class="ni ni-collection d-lg-none"></i>
                    <span class="nav-link-inner--text">Laporan</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="/donasi  " class="nav-link" role="button">
                    <i class="ni ni-collection d-lg-none"></i>
                    <span class="nav-link-inner--text">Donasi</span>
                  </a>
                </li>
                @endif
              <li class="nav-item">
                <a href="/tentang" class="nav-link" role="button">
                  <i class="ni ni-collection d-lg-none"></i>
                  <span class="nav-link-inner--text">Tentang Kami</span>
                </a>
              </li>
              <li class="nav-item dropdown">
                  <a id="navbarDropdown" class="btn btn-neutral btn-icon dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    <span class="btn-inner--icon">
                      <i class="fa fa-user-circle mr-2"></i>
                    </span>
                      {{ Auth::user()->name }} <span class="caret"></span>
                  </a>

                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">
                        Status pengguna: <b>{{ Auth::user()->user_type }}</b>
                    </a>
                      <a class="dropdown-item" href="{{ route('logout') }}"
                         onclick="event.preventDefault();
                                       document.getElementById('logout-form').submit();">
                          {{ __('Logout') }}
                      </a>

                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                          @csrf
                      </form>
                  </div>
              </li>
              @endguest
              <!-- your navbar here -->
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
            @yield('content')
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>
              <li>
                <a href="#">
                  InnoFiction
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright float-right">
            &copy;
            <script>
              document.write(new Date().getFullYear())
            </script>, made with <i class="material-icons">favorite</i> by
            <a href="#" target="_blank">Informatika UII</a> for a better web.
          </div>
          <!-- your footer here -->
        </div>
      </footer>
    </div>
  </div>


  <!-- Core -->
  <script src="{{URL::to('/dashboard')}}/js/core/jquery.min.js"></script>
  <script src="{{URL::to('/dashboard')}}/js/core/popper.min.js"></script>
  <script src="{{URL::to('/dashboard')}}/js/core/bootstrap-material-design.min.js"></script>
  <script src="{{URL::to('/dashboard')}}/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!-- Plugin for the momentJs  -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/moment.min.js"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/sweetalert2.js"></script>
  <!-- Forms Validations Plugin -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/jquery.validate.min.js"></script>
  <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/jquery.bootstrap-wizard.js"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/bootstrap-selectpicker.js"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/bootstrap-datetimepicker.min.js"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/jquery.dataTables.min.js"></script>
  <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/bootstrap-tagsinput.js"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/jasny-bootstrap.min.js"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/fullcalendar.min.js"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/jquery-jvectormap.js"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/nouislider.min.js"></script>
  <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
  <!-- Library for adding dinamically elements -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/arrive.min.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chartist JS -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/chartist.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="{{URL::to('/dashboard')}}/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{{URL::to('/dashboard')}}/js/material-dashboard.js?v=2.1.1" type="text/javascript"></script>
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="{{URL::to('/dashboard')}}/demo/demo.js"></script>

</body>
</html>

resources/views/donasi/show.blade.php
@extends('donasi.layout')

@section('content')

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">Rincian Data Donasi</h4>
              <p class="card-category">Rincian data donasi dalam database</p>
            </div>
            <div class="card-body">
              <div class="col-xs-12 col-sm-12 col-md-12">
                  <div class="form-group">
                      <strong>Name :</strong>
                      {{ $donasi->donatur }}
                  </div>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12">
                  <div class="form-group">
                      <strong>Kontak :</strong>
                      {{ $donasi->kontak }}
                  </div>
              </div>

              <div class="col-xs-12 col-sm-12 col-md-12 text-right pull-right">
                <a class="btn btn-danger" href="{{ route('laporan.index') }}">Kembali</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

@endsection