routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('', 'MasterController@home');
Route::get('/', 'MasterController@home');
Route::get('home', 'MasterController@home');
Route::get('/home', 'MasterController@home');

Route::resource('logistik','LogistikController');
Route::resource('laporan','LaporanController');
Route::resource('kategori','KategoriController');
Route::resource('pengungsi','PengungsiController');
Route::resource('donasi','DonasiController');
// Route::post('laporan.store2', 'LaporanController@store2');
Auth::routes();

Route::get('laporkan', 'MasterController@laporan');
Route::get('donasikan', 'MasterController@donasikan');
Route::post('/laporkan/proses', 'MasterController@store_laporan');
Route::post('/donasi/proses', 'MasterController@store_donasikan');
Route::get('tentang', 'MasterController@tentang');
Route::get('map', 'MasterController@map');
Route::get('dasbor', 'MasterController@dasbor');

app/Logistik.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Logistik extends Model{
  protected $fillable = [
    'id_logistik','nama','stok','kadaluarsa','kategori','daerah','sumber'
  ];
}

?>

app/Http/Controllers/LogistikController.php
<?php

namespace App\Http\Controllers;

use DB;
use App\User;
use App\Pengungsi;
use App\Logistik;
use App\Kategori;
use Illuminate\Http\Request;

class LogistikController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $logistiks = DB::table('logistiks')
                      ->join('kategoris','logistiks.kategori','=','kategoris.id')
                      ->join('pengungsis','logistiks.daerah','=','pengungsis.id')
                      ->join('users','logistiks.sumber','=','users.id')
                      ->select('logistiks.*','kategoris.kategori as nama_kategori','pengungsis.nama_pengungsian')
                      ->paginate('5');

        // dd($logistiks);

        return view('logistik.index',compact('logistiks'))->with('i',(request()->input('page',1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $lokasi = Pengungsi::all();
        $kategori = Kategori::all();
        $user = User::all();

        return view('logistik.create', compact('kategori','lokasi','user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
          'nama' => 'required',
          'stok' => 'required',
          'kadaluarsa' => 'required',
          'kategori' => 'required',
          'daerah' => 'required',
        ]);

        Logistik::create($request->all());

        return redirect()->route('logistik.index')->with('success','Data berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\logistik  $logistik
     * @return \Illuminate\Http\Response
     */
    public function show(logistik $logistik)
    {
        return view('logistik.show',compact('logistik'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\logistik  $logistik
     * @return \Illuminate\Http\Response
     */
    public function edit(logistik $logistik)
    {
        $lokasi = Pengungsi::all();
        $kategori = Kategori::all();
        $user = User::all();
        return view('logistik.edit',compact('logistik','kategori','lokasi','user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\logistik  $logistik
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, logistik $logistik)
    {
        //
        $request->validate([
          'nama' => 'required',
          'stok' => 'required',
          'kadaluarsa' => 'required',
          'kategori' => 'required',
          'daerah' => 'required',
        ]);

        $logistik->update($request->all());

        return redirect()->route('logistik.index')->with('success','Data berhasil disunting.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\logistik  $logistik
     * @return \Illuminate\Http\Response
     */
    public function destroy(logistik $logistik)
    {
        //
        $logistik->delete();

        return redirect()->route('logistik.index')->with('success','Data berhasil dihapus.');
    }
}

resources/views/logistik/create.blade.php
@extends('logistik.layout')
@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">Tambahkan Logistik</h4>
          <p class="card-category">Tambahkan data logistik ke dalam database</p>
        </div>
        <div class="card-body">
          <form action="{{ route('logistik.store') }}" method="POST">
              @csrf
               <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Nama Logistik:</strong>
                          <input type="text" name="nama" class="form-control" placeholder="Name">
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Stok:</strong>
                          <input type="text" class="form-control" name="stok" placeholder="stok">
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Kadaluarsa:</strong>
                          <input type="date" class="form-control" name="kadaluarsa" placeholder="kadaluarsa">
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Kategori:</strong>
                          <select class="form-control" name="kategori">
                            <option value="">Pilih Kebutuhan</option>
                            @foreach ($kategori as $product)
                            <option value="{{$product->id}}">{{$product->kategori}}</option>
                            @endforeach
                          </select>
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Daerah:</strong>
                          <!-- <input type="text" class="form-control" name="daerah" placeholder="daerah"> -->
                          <select class="form-control" name="daerah">
                            <option value="">Pilih Tempat Pengungsian</option>
                            @foreach ($lokasi as $item)
                            <option value="{{$item->id}}">{{$item->nama_pengungsian}}</option>
                            @endforeach
                          </select>
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Sumber Logistik:</strong>
                          <!-- <input type="text" class="form-control" name="daerah" placeholder="daerah"> -->
                          <select class="form-control" name="sumber">
                            <option value="">Pilih Pemberi Logistik</option>
                            @foreach ($user as $item)
                            <option value="{{$item->id}}">{{$item->name}}</option>
                            @endforeach
                          </select>
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12 text-right pull-right">
                          <button type="submit" class="btn btn-success">Simpan</button>
                          <a class="btn btn-danger" href="{{ route('logistik.index') }}"> Kembali</a>
                  </div>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/logistik/edit.blade.php
@extends('logistik.layout')

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">Sunting Data Logistik</h4>
              <p class="card-category">Sunting data logistik dalam database</p>
            </div>
            <div class="card-body">
          <form action="{{ route('logistik.update',$logistik->id) }}" method="POST">
              @csrf
              @method('PUT')

               <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Name:</strong>
                          <input type="text" name="nama" value="{{ $logistik->nama }}" class="form-control" placeholder="Name">
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Stok:</strong>
                          <input type="text" class="form-control" value="{{ $logistik->stok }}" name="stok" placeholder="stok">
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Kadaluarsa:</strong>
                          <input type="date" class="form-control" value="{{ $logistik->kadaluarsa }}" name="kadaluarsa" placeholder="kadaluarsa">
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Kategori:</strong>
                          <select class="form-control" name="kategori">
                            <!-- <option value="{{$logistik->kategori}}">{{$logistik->nama_kategori}}</option> -->
                            @foreach ($kategori as $item)
                            @if($item->id == $logistik->kategori)
                            <option value="{{$item->id}}" selected>{{$item->kategori}}</option>
                            @else
                            <option value="{{$item->id}}">{{$item->kategori}}</option>
                            @endif

                            @endforeach
                          </select>
                          <!-- <input type="text" class="form-control" value="{{ $logistik->kategori }}" name="kategori" placeholder="kategori"> -->
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Daerah:</strong>
                          <!-- <input type="text" class="form-control" value="{{ $logistik->daerah }}" name="daerah" placeholder="daerah"> -->
                          <select class="form-control" name="daerah">
                            <!-- <option value="{{$logistik->kategori}}">{{$logistik->nama_kategori}}</option> -->
                            @foreach ($lokasi as $item)
                            @if($item->id == $logistik->daerah)
                            <option value="{{$item->id}}" selected>{{$item->nama_pengungsian}}</option>
                            @else
                            <option value="{{$item->id}}">{{$item->nama_pengungsian}}</option>
                            @endif

                            @endforeach
                          </select>
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12">
                      <div class="form-group">
                          <strong>Sumber Logistik:</strong>
                          <!-- <input type="text" class="form-control" name="daerah" placeholder="daerah"> -->
                          <select class="form-control" name="sumber">
                            <option value="">Pilih Pemberi Logistik</option>
                            @foreach ($user as $item)
                            @if($item->id == $logistik->sumber)
                            <option value="{{$item->id}}" selected>{{$item->name}}</option>
                            @else
                            <option value="{{$item->id}}">{{$item->name}}</option>
                            @endif
                            @endforeach
                          </select>
                      </div>
                  </div>
                  <div class="col-xs-12 col-sm-12 col-md-12 text-right pull-right">
                          <button type="submit" class="btn btn-success">Simpan</button>
                          <a class="btn btn-danger" href="{{ route('logistik.index') }}"> Kembali</a>
                  </div>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/logistik/index.blade.php
@extends('logistik.layout')

@section('content')

<script>
function cari() {
// Declare variables
var input, filter, table, tr, td, i;
input = document.getElementById("input_search");
filter = input.value.toUpperCase();
table = document.getElementById("contentTable");
tr = table.getElementsByTagName("tr");

// Loop through all table rows, and hide those who don't match the search query
for (i = 0; i < tr.length; i++) {
	td = tr[i].getElementsByTagName("td")[5];
	if (td) {
		if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
			tr[i].style.display = "";
		} else {
			tr[i].style.display = "none";
		}
	}
}
}
</script>


    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
            </div>
            <div class="pull-right">

            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <script>swal("{{ $message }}","","success")</script>

    @endif
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">

            <div class="row">
              <div class="col-md-9">
                  <h4 class="card-title ">Data Logistik</h4>
                  <p class="card-category"> Berikut merupakan data ketersediaan logistik</p>
              </div>
              <div class="col-md-3 pull-right">
                @guest
                @else
                  @if(Auth::user()->user_type=='BPBD')
                  <a class="btn btn-success" href="{{ route('logistik.create') }}"> Tambah Logistik</a>
                  @endif
                @endguest
                <input type="text" class="form-control text-white" id="input_search" onkeyup="cari()" placeholder="Pencarian berdasarkan daerah">
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table" id="contentTable">
                  <tr>
                      <th>No</th>
                      <!-- <th>ID</th> -->
                      <th>Nama</th>
                      <th>Stok</th>
                      <th>Kadaluarsa</th>
                      <th>Kategori</th>
                      <th>Daerah</th>
                      <th width="280px">Action</th>
                  </tr>
                  @foreach ($logistiks as $product)
                  <tr>
                      <td>{{ ++$i }}</td>
                      <!-- <td>{{ $product->id }}</td> -->
                      <td>{{ $product->nama }}</td>
                      <td>{{ $product->stok }}</td>
                      <td>{{ $product->kadaluarsa }}</td>
                      <td>{{ $product->nama_kategori }}</td>
                      <td>{{ $product->nama_pengungsian }}</td>
                      <td>
                          <form action="{{ route('logistik.destroy',$product->id) }}" method="POST">
                              <a class="btn btn-info" href="{{ route('logistik.show',$product->id) }}"><i class="material-icons">search</i></a>
                              @guest
                              @else
                                @if(Auth::user()->user_type=='BPBD')
                              <a class="btn btn-primary" href="{{ route('logistik.edit',$product->id) }}"><i class="material-icons">edit</i></a>
                              @csrf
                              @method('DELETE')
                              <button type="submit" class="btn btn-danger" onclick="return confirmDelete()"><i class="material-icons">delete</i></button>
                              @endif
                            @endguest
                          </form>
                      </td>
                  </tr>
                  @endforeach
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>


  <script>
    function confirmDelete(){
      event.preventDefault();
      Swal({
        title: 'Apakah anda yakin?',
        text: "Data yang dihapus tidak dapat dikembalikan",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Hapus',
        cancelButtonText: 'Batal',
      }).then((result) => {
        if (result.value) {
          Swal(
            'Data berhasil dihapus!',
            '',
            'success'
          )
          return true;
        }else{
          return false;
        }
        })
      }
</script>

    {!! $logistiks->links() !!}
@endsection

resources/views/logistik/show.blade.php
@extends('logistik.layout')

@section('content')

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title">Rincian Data Logistik</h4>
              <p class="card-category">Rincian data logistik dalam database</p>
            </div>
            <div class="card-body">
              <div class="col-xs-12 col-sm-12 col-md-12">
                  <div class="form-group">
                      <strong>Name:</strong>
                      {{ $logistik->nama }}
                  </div>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12">
                  <div class="form-group">
                      <strong>Stok:</strong>
                      {{ $logistik->stok }}
                  </div>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12 text-right pull-right">
                <a class="btn btn-danger" href="{{ route('logistik.index') }}"> Kembali</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

@endsection